//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoliday
    {
        public int ID { get; set; }
        public string HOLIDAY_NAME { get; set; }
        public string HOLIDAY_TYPE { get; set; }
        public System.DateTime HOLIDAY_DATE { get; set; }
        public string HOLIDAY_DAY { get; set; }
        public string HOLIDAY_DESC { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string STATUS { get; set; }
        public string CITY { get; set; }
    }
}
